spring:
  application:
    name: graphql-backend

server:
  port: 8081
  http2:
    enabled: true


graphql:
  servlet:
    # Sets if GraphQL servlet should be created and exposed. If not specified defaults to "true".
    enabled: true
    # Sets the path where GraphQL servlet will be exposed. If not specified defaults to "/graphql"
    mapping: /graphql
    cors-enabled: true
    cors:
      allowed-origins: http://some.domain.com
      allowed-methods: GET, HEAD, POST
  playground:
    mapping: /playground
    endpoint: /graphql
    enabled: true


